"""kanon churn slavonic name

Revision ID: 29f04137323b
Revises: aa69a0af2d1f
Create Date: 2024-07-15 16:26:18.682068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '29f04137323b'
down_revision: Union[str, None] = 'aa69a0af2d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kanon', sa.Column('slavonic_name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kanon', 'slavonic_name')
    # ### end Alembic commands ###
